### ISSUE TITLE
Add subtitle support

### ISSUE THREAD

**Issue by vividuzv** [MohamedBakoush/WatchVideoByLink#63]
Thanks for the app.

is it possible to add subtitle upload and subtitle options ( color - size - font , ... ) to app ? 

thanks.

**Comment by MohamedBakoush** [comment]
It would be possible, but would require some work.

**Some questions to answer before committing towards the feature**
Who would be implementing this? me, you or a combination of both
What would the UI and UX be like from uploading to consuming a video with subtitles?
Which subtitle file format would be supported?
Which subtitle options would be supported? - only colour, size and font?
Default subtitle option? 

**Rough idea on how to implant**

Manually upload subtitles 
 - client: upload subtitles button - available at video edit mode
 - backend: upload subtitle file to specified video folder
 - backend: connect subtitles with related video database
 - client: [if subtitles detected after opening video add text tracks](https://docs.videojs.com/tutorial-text-tracks.html)
 - backend: When video gets delete make sure subtitles also get deleted

Subtitle options
 - backend: Add different subtitle settings - user-settings.json
 - client: There is no global UI settings but if there were subtitle options would be their

**Comment by MohamedBakoush** [comment]
If a proper response is not given in the 7 days i'll assume there no longer interest for subtitle support and this Issue will get closed.

**Comment by MohamedBakoush** [comment]
lack of information
